In [1]:
import matplotlib.pyplot as plt
import torch
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit

from torch.utils.data import Dataset, DataLoader

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Sample_20210716.csv')


In [4]:
df

Unnamed: 0           Sr         Time     kW  Load Detected  AC Detected  \
0              0  43001931690  12:00:00 AM  1.454              0            0   
1              1  43001931690  12:01:00 AM  1.442              0            0   
2              2  43001931690  12:02:00 AM  1.455              0            0   
3              3  43001931690  12:03:00 AM  1.453              0            0   
4              4  43001931690  12:04:00 AM  1.357              0            0   
...          ...          ...          ...    ...            ...          ...   
1427        1427  43001931690  11:55:00 PM  1.518              1            1   
1428        1428  43001931690  11:56:00 PM  1.535              1            1   
1429        1429  43001931690  11:57:00 PM  1.537              1            1   
1430        1430  43001931690  11:58:00 PM  1.535              1            1   
1431        1431  43001931690  11:59:00 PM  1.534              1            1   

      Motor  Microwave  result  
0         0          0       0  
1         0          0       0  
2         0          0       0  
3         0          0       0  
4         0          0       0  
...     ...        ...     ...  
1427      0          0       1  
1428      0          0       1  
1429      0          0       1  
1430      0          0       1  
1431      0          0       1  

[1432 rows x 9 columns]

In [5]:
x = df.iloc[:,3:5].values

In [6]:
x

array([[1.454, 0.   ],
       [1.442, 0.   ],
       [1.455, 0.   ],
       ...,
       [1.537, 1.   ],
       [1.535, 1.   ],
       [1.534, 1.   ]])

In [7]:
y = df.iloc[:,-1].values

In [8]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [9]:
#separate the features into training, testing and validation

In [10]:
ss = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 31)

In [11]:
for train_index, group_index in ss.split(x,y):
    xtrain, xgroup = x[train_index], x[group_index]
    ytrain, ygroup = y[train_index], y[group_index]

In [12]:
ss = StratifiedShuffleSplit(n_splits = 1, test_size = 0.5, random_state = 31)
for test_index, valid_index in ss.split(xgroup, ygroup):
    xtest, xvalid = xgroup[test_index], xgroup[valid_index]
    ytest, yvalid = ygroup[test_index], ygroup[valid_index]

In [13]:
xtest

array([[1.402, 1.   ],
       [0.421, 0.   ],
       [0.489, 0.   ],
       [0.465, 0.   ],
       [0.32 , 0.   ],
       [0.334, 0.   ],
       [1.292, 1.   ],
       [1.404, 1.   ],
       [1.46 , 1.   ],
       [0.466, 1.   ],
       [0.509, 0.   ],
       [0.404, 0.   ],
       [1.443, 1.   ],
       [0.528, 0.   ],
       [0.372, 0.   ],
       [0.472, 1.   ],
       [0.326, 0.   ],
       [0.339, 0.   ],
       [0.413, 0.   ],
       [1.364, 0.   ],
       [0.469, 0.   ],
       [1.461, 1.   ],
       [0.339, 0.   ],
       [1.454, 1.   ],
       [0.466, 0.   ],
       [0.505, 0.   ],
       [0.473, 0.   ],
       [0.419, 0.   ],
       [0.932, 1.   ],
       [0.474, 0.   ],
       [0.414, 0.   ],
       [0.406, 0.   ],
       [0.393, 0.   ],
       [1.579, 0.   ],
       [1.527, 1.   ],
       [0.433, 0.   ],
       [1.288, 1.   ],
       [0.489, 1.   ],
       [0.355, 0.   ],
       [0.426, 0.   ],
       [1.442, 1.   ],
       [0.466, 0.   ],
       [1.457, 1.   ],
       [0.5

In [14]:
#let us standardize the features

In [15]:
sc = StandardScaler()

In [16]:
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)
xvalid = sc.transform(xvalid)

In [17]:
#convering into the tensors

In [18]:
xtrain, xtest, xvalid = map(torch.tensor, (xtrain, xtest, xvalid))

In [19]:
ytrain, ytest, yvalid = map(torch.tensor, (ytrain, ytest, yvalid))

In [20]:
#making the tensors dtype to float for features( x values )

In [21]:
xtrain = xtrain.float()
xtest = xtest.float()
xvalid = xvalid.float()

In [22]:
#prepare to load the xtrain dataset by dividing it into small chunks

In [23]:
class dds(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __getitem__(self,index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return len(self.x)
    

In [36]:
mydata = dds(xtrain, ytrain)
train_loader = DataLoader(dataset = mydata, batch_size = 10)
print(xtrain)

tensor([[ 1.3606,  1.2799],
        [ 1.4668,  1.2799],
        [-0.7485, -0.7813],
        [ 1.3565,  1.2799],
        [-0.8037, -0.7813],
        [-0.4522, -0.7813],
        [-0.6974, -0.7813],
        [-0.6157, -0.7813],
        [-0.5094, -0.7813],
        [-0.1354, -0.7813],
        [-0.5728, -0.7813],
        [ 1.0540,  1.2799],
        [-0.9386, -0.7813],
        [-0.8568, -0.7813],
        [-0.6770, -0.7813],
        [-0.8139, -0.7813],
        [-1.1675, -0.7813],
        [ 1.3483,  1.2799],
        [-0.6852,  1.2799],
        [-0.7771, -0.7813],
        [-0.9794, -0.7813],
        [ 1.3912,  1.2799],
        [-0.7649, -0.7813],
        [ 1.1705,  1.2799],
        [ 1.2277,  1.2799],
        [-0.7935, -0.7813],
        [ 1.3136,  1.2799],
        [ 0.3183,  1.2799],
        [-0.9835, -0.7813],
        [-0.7506, -0.7813],
        [-0.5891, -0.7813],
        [ 1.3258,  1.2799],
        [-0.7914, -0.7813],
        [ 1.2420,  1.2799],
        [-0.6770, -0.7813],
        [ 1.0356,  1

In [25]:
# creating the neural network Arc

In [26]:
class FeedForward(torch.nn.Module):
    def __init__(self, n_inputs, n_outputs, hidden_size):
        super(FeedForward, self).__init__()
        self.inputs = n_inputs
        self.outputs = n_outputs
        self.hidden = hidden_size
        
        self.fc1 = torch.nn.Linear(self.inputs, self.hidden)
        self.fc2 = torch.nn.Linear(self.hidden, self.hidden)
        self.fc3 = torch.nn.Linear(self.hidden, self.hidden)
        self.fc4 = torch.nn.Linear(self.hidden, self.hidden)
        self.fc5 = torch.nn.Linear(self.hidden, self.outputs)
        
        self.relu = torch.nn.ReLU()
        
        self.init_weights()
        
    def init_weights(self):
        torch.nn.init.kaiming_normal_(self.fc1.weight)
        torch.nn.init.kaiming_normal_(self.fc2.weight)
        torch.nn.init.kaiming_normal_(self.fc3.weight)
        torch.nn.init.kaiming_normal_(self.fc4.weight)
        torch.nn.init.kaiming_normal_(self.fc5.weight)
        
    def forward(self, features):
        output = self.fc1(features)
        output = self.relu(output)
        output = self.fc2(output)
        output = self.relu(output)
        output = self.fc3(output)
        output = self.relu(output)
        output = self.fc4(output)
        output = self.relu(output)
        output = self.fc5(output)
        return output

In [49]:
model = FeedForward(n_inputs = xtrain.shape[1], n_outputs=4, hidden_size = 200)

criterion = torch.nn.CrossEntropyLoss(reduction= 'mean')

optimizer = torch.optim.SGD(params = model.parameters(), lr= .001, momentum = 0.9)

In [50]:
#train the network
torch.set_printoptions(profile="full")
print(ytrain)

tensor([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 3, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 3, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,

In [51]:
epochs = 20
valid_accuracy = [0]

for epoch in range(epochs):
    for features, targets in train_loader:
        output = model.forward(features)
        loss = criterion(output, targets)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    model.eval()
    
    c = torch.argmax(output.data, dim = 1)
    train_accuracy = (c == targets).sum().item()/targets.shape[0]
    print('accuracy', train_accuracy)
    
    model.train()

accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
accuracy 1.0
